[[constraint]]
  branch = "master"
  name = "github.com/ajstarks/svgo"

[[constraint]]
  name = "github.com/fredericlemoine/bitset"
  version = "1.2.0"

[[constraint]]
  name = "github.com/evolbioinfo/goalign"
  version = ">=v0.3.1-alpha"
  #revision = "ab854d8a691112edd3c4d8a90fd751d9878bb44c"
  #branch="dev"

[[constraint]]
  name = "github.com/fredericlemoine/gostats"
  revision = "e750742f8b05a600f247b0f866a10e41d0a2128c"

[[constraint]]
  branch = "master"
  name = "github.com/fredericlemoine/cobrashell"

[[constraint]]
  branch = "master"
  name = "github.com/golang/freetype"

[[constraint]]
  branch = "master"
  name = "github.com/jlaffaye/ftp"

[[constraint]]
  name = "github.com/llgcode/draw2d"
  revision = "274031cf2abe8acd15c4a911e1f7f1295fc4830c"
  
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"

