# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/ajstarks/svgo"

[[constraint]]
  name = "github.com/fredericlemoine/bitset"
  version = "1.2.0"

[[constraint]]
  name = "github.com/fredericlemoine/goalign"
  version = "0.2.4"

[[constraint]]
  name = "github.com/fredericlemoine/gostats"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/freetype"

[[constraint]]
  branch = "master"
  name = "github.com/jlaffaye/ftp"

[[constraint]]
  branch = "master"
  name = "github.com/llgcode/draw2d"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"
